djangoprj/dateapp/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path("",views.dateshome,name="dateshome")
]

djangoprj/djangoapp/urls.py
from django.urls import path
from . import views

urlpatterns= [
    path("",views.home,name="Homepage"),
    path("hello",views.hello,name="HW"),
    #path("<str:nam>",views.name,name="Helloname"),
    path("<str:nam>",views.renderhtml,name="Hi Name")    
]

djangoprj/djangoprj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include("djangoapp.urls")),
    path('dateapp/', include("dateapp.urls")),
    path('tasksapp/', include("tasksapp.urls")),
]

djangoprj/tasksapp/urls.py
from django.urls import path
from . import views

app_name= "tasksapp"
urlpatterns = [
    path("", views.homepagetask, name="homepagetask"),
    path("add", views.add, name="add"),
]

djangoprj/dateapp/models.py
from django.db import models

# Create your models here.

djangoprj/djangoapp/models.py
from django.db import models

# Create your models here.

djangoprj/tasksapp/models.py
from django.db import models

# Create your models here.

djangoprj/dateapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
import datetime
# Create your views here.
def dateshome(request):
    curdate = datetime.datetime.now()
    y=curdate.year
    m=curdate.month
    d=curdate.day
    h=curdate.hour
    m=curdate.minute
    s=curdate.second
    boolvar = y == 1 and m == 1
    return render(request,"dateapp/datecheck.html",{"ye":y,"mo":m,"da":d,"ho":h,"mi":m,"se":s,"boolvariable":boolvar})

djangoprj/djangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home(request):
    return HttpResponse("Homepage!")

def hello(request):
    return HttpResponse("Hello, world!")

#def name(request,nam):
#   return HttpResponse(f"Hello, {nam.capitalize()}!")

def renderhtml(request,nam):
    return render(request,"djangoapp/render.html",{"name":nam.capitalize()})

djangoprj/tasksapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.urls import reverse

class Newform(forms.Form):
    task = forms.CharField(label="NewTask")
    #priority = forms.IntegerField(label="Priority", min_value=1,max_value=10)

tasks = ["hey", "hi", "hello"]
# Create your views here.
def homepagetask(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "tasksapp/taskapptemplate.html", {"tasksvar":request.session["tasks"]})

def add(request):
    if request.method == "POST":
        filledform = Newform(request.POST)
        if filledform.is_valid():
            task = filledform.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasksapp:homepagetask"))
        else:
            return render(request,"tasksapp/add.html",{"newformvar":filledform})

    return render(request, "tasksapp/add.html", {"newformvar":Newform()})

djangoprj/dateapp/templates/dateapp/datecheck.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>
            Date Current
        </title>
        <link href="{% static 'dateapp/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="cen">{{ye}}-{{mo}}-{{da}}</div>
        <div class="cen">{{ho}}-{{mi}}-{{se}}</div>
        {% if boolvariable %}
            <div class="cen">Happy New Year</div>
        {% else %}
            <div class="cen"> Have a good day.</div>
        {% endif %}
    </body>
</html>

djangoprj/djangoapp/templates/djangoapp/render.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Rendered html template</title>
</head>
<body>
    <h1>Hi {{name}}</h1>
</body>
</html>

djangoprj/tasksapp/templates/tasksapp/add.html
{% extends "tasksapp/layout.html" %}
{% block body %}
    <h1>Add task</h1>
    <form action="{% url 'tasksapp:add' %}" method="post">
        {% csrf_token %}
        <!--<input type="text" name="newtask">-->
        {{newformvar}}
        <input type="submit"> 
    </form>
    <a href="{% url 'tasksapp:homepagetask' %}"> View Tasks </a>
    <br>
{% endblock %}

djangoprj/tasksapp/templates/tasksapp/layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>
            Tasks
        </title>
        <link href="{% static 'tasksapp/styles.css' %}" rel="stylesheet">
    </head>
        <body>
            {% block body %}
            {% endblock %}
        </body>
</html>

djangoprj/tasksapp/templates/tasksapp/taskapptemplate.html
{% extends "tasksapp/layout.html" %}
{% block body %}
    <ul class="cen">
        {% for task in tasksvar %}
        <li>{{task}}</li>
        {% empty %}
        <li>No Tasks</li>
        {% endfor %}
    </ul>
    <a href="{% url 'tasksapp:add' %}">Add Task</a>
{% endblock %}